language: python

services:
  - docker

install:
  - docker build -t docker-tesseract .

script:
  - docker run -v `pwd`/test:/exchange docker-tesseract eng_bw.png test_output txt
  - docker run -v `pwd`/test:/exchange docker-tesseract eng_bw.png test_output pdf
